version: '3.8'
services:
  client:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - "../../:/workspace"
    ports:
      - "3000:3000"
    tty: true
    networks:
      - accomplist_link

networks:
  accomplist_link:
    external: true
